### ISSUE TITLE
please disable default features of chrono

### ISSUE THREAD

**Issue by zseri** [rust-syndication/atom#56]
(at least disable the `clock` feature, because of https://github.com/chronotope/chrono/issues/499, which makes auditing more cumbersome, checking if a feature is disabled is easier than needing to grep all the code)

e.g.
```toml
[dependencies.chrono]
version = "0.4"
default-features = false
features = ["alloc"]
```
